using System;
using System.Diagnostics.CodeAnalysis;

namespace JLeb.Estragonia;

/// <summary>Contains some used Vulkan constants.</summary>
[SuppressMessage("ReSharper", "InconsistentNaming")]
internal static class VkConstants {

	internal enum VkImageLayout {
		// Provided by VK_VERSION_1_0
		UNDEFINED = 0,
		GENERAL = 1,
		COLOR_ATTACHMENT_OPTIMAL = 2,
		DEPTH_STENCIL_ATTACHMENT_OPTIMAL = 3,
		DEPTH_STENCIL_READ_ONLY_OPTIMAL = 4,
		SHADER_READ_ONLY_OPTIMAL = 5,
		TRANSFER_SRC_OPTIMAL = 6,
		TRANSFER_DST_OPTIMAL = 7,
		PREINITIALIZED = 8,

		// Provided by VK_VERSION_1_1
		DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL = 1000117000,
		DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL = 1000117001,

		// Provided by VK_VERSION_1_2
		DEPTH_ATTACHMENT_OPTIMAL = 1000241000,
		DEPTH_READ_ONLY_OPTIMAL = 1000241001,
		STENCIL_ATTACHMENT_OPTIMAL = 1000241002,
		STENCIL_READ_ONLY_OPTIMAL = 1000241003,

		// Provided by VK_VERSION_1_3
		READ_ONLY_OPTIMAL = 1000314000,
		ATTACHMENT_OPTIMAL = 1000314001,

		// Provided by VK_KHR_swapchain
		PRESENT_SRC_KHR = 1000001002,

		// Provided by VK_KHR_video_decode_queue
		VIDEO_DECODE_DST_KHR = 1000024000,
		VIDEO_DECODE_SRC_KHR = 1000024001,
		VIDEO_DECODE_DPB_KHR = 1000024002,

		// Provided by VK_KHR_shared_presentable_image
		SHARED_PRESENT_KHR = 1000111000,

		// Provided by VK_EXT_fragment_density_map
		FRAGMENT_DENSITY_MAP_OPTIMAL_EXT = 1000218000,

		// Provided by VK_KHR_fragment_shading_rate
		FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR = 1000164003,

		// Provided by VK_KHR_video_encode_queue
		VIDEO_ENCODE_DST_KHR = 1000299000,
		VIDEO_ENCODE_SRC_KHR = 1000299001,
		VIDEO_ENCODE_DPB_KHR = 1000299002,

		// Provided by VK_EXT_attachment_feedback_loop_layout
		ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT = 1000339000,

		// Provided by VK_KHR_maintenance2
		DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR = DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL,
		DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR = DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL,

		// Provided by VK_NV_shading_rate_image
		SHADING_RATE_OPTIMAL_NV = FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR,

		// Provided by VK_KHR_separate_depth_stencil_layouts
		DEPTH_ATTACHMENT_OPTIMAL_KHR = DEPTH_ATTACHMENT_OPTIMAL,
		DEPTH_READ_ONLY_OPTIMAL_KHR = DEPTH_READ_ONLY_OPTIMAL,
		STENCIL_ATTACHMENT_OPTIMAL_KHR = STENCIL_ATTACHMENT_OPTIMAL,
		STENCIL_READ_ONLY_OPTIMAL_KHR = STENCIL_READ_ONLY_OPTIMAL,

		// Provided by VK_KHR_synchronization2
		READ_ONLY_OPTIMAL_KHR = READ_ONLY_OPTIMAL,

		// Provided by VK_KHR_synchronization2
		ATTACHMENT_OPTIMAL_KHR = ATTACHMENT_OPTIMAL
	}

	internal enum VkImageTiling {
		// Provided by VK_VERSION_1_0
		OPTIMAL = 0,
		LINEAR = 1,

		// Provided by VK_EXT_image_drm_format_modifier
		DRM_FORMAT_MODIFIER_EXT = 1000158000
	}

	[Flags]
	internal enum VkImageUsageFlagBits {
		// Provided by VK_VERSION_1_0
		TRANSFER_SRC_BIT = 0x00000001,
		TRANSFER_DST_BIT = 0x00000002,
		SAMPLED_BIT = 0x00000004,
		STORAGE_BIT = 0x00000008,
		COLOR_ATTACHMENT_BIT = 0x00000010,
		DEPTH_STENCIL_ATTACHMENT_BIT = 0x00000020,
		TRANSIENT_ATTACHMENT_BIT = 0x00000040,
		INPUT_ATTACHMENT_BIT = 0x00000080,

		// Provided by VK_KHR_video_decode_queue
		VIDEO_DECODE_DST_BIT_KHR = 0x00000400,
		VIDEO_DECODE_SRC_BIT_KHR = 0x00000800,
		VIDEO_DECODE_DPB_BIT_KHR = 0x00001000,

		// Provided by VK_EXT_fragment_density_map
		FRAGMENT_DENSITY_MAP_BIT_EXT = 0x00000200,

		// Provided by VK_KHR_fragment_shading_rate
		FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR = 0x00000100,

		// Provided by VK_KHR_video_encode_queue
		VIDEO_ENCODE_DST_BIT_KHR = 0x00002000,
		VIDEO_ENCODE_SRC_BIT_KHR = 0x00004000,
		VIDEO_ENCODE_DPB_BIT_KHR = 0x00008000,

		// Provided by VK_EXT_attachment_feedback_loop_layout
		ATTACHMENT_FEEDBACK_LOOP_BIT_EXT = 0x00080000,

		// Provided by VK_HUAWEI_invocation_mask
		INVOCATION_MASK_BIT_HUAWEI = 0x00040000,

		// Provided by VK_QCOM_image_processing
		SAMPLE_WEIGHT_BIT_QCOM = 0x00100000,
		SAMPLE_BLOCK_MATCH_BIT_QCOM = 0x00200000,

		// Provided by VK_NV_shading_rate_image
		SHADING_RATE_IMAGE_BIT_NV = FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR
	}

	internal enum VkSharingMode {
		// Provided by VK_VERSION_1_0
		EXCLUSIVE = 0,
		CONCURRENT = 1
	}

}